/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kopapirollo;

import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author NagyEszterErzsébet(S
 */
public class KoPapirOlloGUI extends javax.swing.JFrame {

    /**
     * Creates new form KoPapirOlloGUI
     */
    public KoPapirOlloGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlKoPapirOllo = new javax.swing.JPanel();
        lblValasszKI = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRendben = new javax.swing.JButton();
        lblGepTippje = new javax.swing.JLabel();
        lblEredmeny = new javax.swing.JLabel();
        rbtnKo = new javax.swing.JRadioButton();
        rbtnPapir = new javax.swing.JRadioButton();
        rbtnOllo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Játszunk kő,papír,ollót!");
        setMinimumSize(new java.awt.Dimension(300, 400));

        pnlKoPapirOllo.setBorder(javax.swing.BorderFactory.createTitledBorder("Kő, papír, olló"));

        lblValasszKI.setText("Válassz ki egyet:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnRendben.setText("Rendben");
        btnRendben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendbenActionPerformed(evt);
            }
        });

        lblGepTippje.setText("...");
        lblGepTippje.setBorder(javax.swing.BorderFactory.createTitledBorder("A gép tippje: "));

        lblEredmeny.setText("...");
        lblEredmeny.setBorder(javax.swing.BorderFactory.createTitledBorder("A játék eredménye: "));

        buttonGroup1.add(rbtnKo);
        rbtnKo.setText("Kő");

        buttonGroup1.add(rbtnPapir);
        rbtnPapir.setText("Papír");

        buttonGroup1.add(rbtnOllo);
        rbtnOllo.setText("Olló");

        javax.swing.GroupLayout pnlKoPapirOlloLayout = new javax.swing.GroupLayout(pnlKoPapirOllo);
        pnlKoPapirOllo.setLayout(pnlKoPapirOlloLayout);
        pnlKoPapirOlloLayout.setHorizontalGroup(
            pnlKoPapirOlloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKoPapirOlloLayout.createSequentialGroup()
                .addGroup(pnlKoPapirOlloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKoPapirOlloLayout.createSequentialGroup()
                        .addComponent(btnRendben)
                        .addGap(132, 132, 132)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKoPapirOlloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblValasszKI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnKo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnPapir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnOllo))
                    .addComponent(lblEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGepTippje, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlKoPapirOlloLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRendben, jPanel2, lblValasszKI});

        pnlKoPapirOlloLayout.setVerticalGroup(
            pnlKoPapirOlloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKoPapirOlloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKoPapirOlloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValasszKI)
                    .addComponent(rbtnKo)
                    .addComponent(rbtnPapir)
                    .addComponent(rbtnOllo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKoPapirOlloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRendben))
                .addGap(18, 18, 18)
                .addComponent(lblGepTippje, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlKoPapirOllo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKoPapirOllo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRendbenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendbenActionPerformed
        int gt = gepTippje();
        int felhasznalo_tipp = 0;
        if (rbtnKo.isSelected()) {
            felhasznalo_tipp = 1;
        } else if (rbtnPapir.isSelected()) {
            felhasznalo_tipp = 2;
        } else if (rbtnOllo.isSelected()) {
            felhasznalo_tipp = 3;
        }
        eredmeny(gt, felhasznalo_tipp);
    }//GEN-LAST:event_btnRendbenActionPerformed
    private int gepTippje() {
        Random random = new Random();
        int gTippje = random.nextInt(3) + 1;
        String gepSzoveg ="";
        switch (gTippje) {
            case 1:
                gepSzoveg="Kő";
                break;
            case 2:
                gepSzoveg="Papír";
                break;
            case 3:
                gepSzoveg="Olló";
                break;
            default:
                break;
        }
        lblGepTippje.setText(gepSzoveg);
        return gTippje;
    }

    private void eredmeny(int gepTippje, int felhasznalo_tipp) {
        String eredmenyszoveg = "";
        if (felhasznalo_tipp - gepTippje == 1 || felhasznalo_tipp - gepTippje == -2) {
            eredmenyszoveg ="Nyertél!";
        }
        else if(felhasznalo_tipp == gepTippje) {
            eredmenyszoveg ="Döntetlen!";
        }
        else{
            eredmenyszoveg="Sajnos vesztettél!";
        }
        lblEredmeny.setText(eredmenyszoveg);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KoPapirOlloGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KoPapirOlloGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KoPapirOlloGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KoPapirOlloGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KoPapirOlloGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRendben;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEredmeny;
    private javax.swing.JLabel lblGepTippje;
    private javax.swing.JLabel lblValasszKI;
    private javax.swing.JPanel pnlKoPapirOllo;
    private javax.swing.JRadioButton rbtnKo;
    private javax.swing.JRadioButton rbtnOllo;
    private javax.swing.JRadioButton rbtnPapir;
    // End of variables declaration//GEN-END:variables
}
